"""`Data/INDEX.md`: one page that says which posting has a tailored CV and which does not.

Folders under `Data/<Source>/<Company>/<Role>/` are the source of truth, and
moving them breaks `jd-write` path resolution and `jd-similar`. So status is
computed from what is on disk, never stored: a posting is `tailored` when
`cv.pdf` and `cover-letter.pdf` both exist, `in progress` when a
`requirements-map.md` exists without them, and `todo` otherwise. Score,
work authorization and the apply link come from the queue row that
`.jobmeta.json`'s `row_key` names.
"""

import json
import os

import jobq

_ORDER = {"tailored": 0, "in progress": 1, "todo": 2, "blocked": 3}


def _status(folder, work_authorization):
    names = [n.lower() for n in os.listdir(folder)]
    has = lambda name: name in names  # noqa: E731
    named_cv = any("-cv-" in n and n.endswith(".pdf") for n in names)
    named_letter = any("-cover-letter-" in n and n.endswith(".pdf") for n in names)
    if (named_cv and named_letter) or (has("cv.pdf") and has("cover-letter.pdf")):
        return "tailored"
    if work_authorization == "closed":
        return "blocked"
    if has("requirements-map.md"):
        return "in progress"
    return "todo"


def collect(root, queue_rows):
    by_key = {jobq.row_key(r): r for r in queue_rows}
    entries = []
    for dirpath, _dirs, files in os.walk(root):
        if "JD.md" not in files:
            continue
        row = {}
        try:
            with open(os.path.join(dirpath, ".jobmeta.json"), encoding="utf-8") as f:
                meta = json.load(f)
            row = by_key.get(meta.get("row_key"), {})
        except (OSError, json.JSONDecodeError):
            meta = {}
        wa = row.get("work_authorization") or "-"
        entries.append(
            {
                "path": os.path.relpath(dirpath, root),
                "company": meta.get("company") or row.get("company") or "?",
                "role": meta.get("jobTitle") or row.get("jobTitle") or "?",
                "source": meta.get("source") or row.get("source") or "?",
                "score": row.get("fit_score"),
                "work_authorization": wa,
                "apply": meta.get("jobUrl") or row.get("jobUrl") or "",
                "status": _status(dirpath, wa),
            }
        )
    entries.sort(key=lambda e: (_ORDER[e["status"]], -(e["score"] if e["score"] is not None else -1), e["company"]))
    return entries


def render(entries):
    counts = {s: sum(1 for e in entries if e["status"] == s) for s in _ORDER}
    lines = [
        "# Data index",
        "",
        "Generated by `data-index`. Do not edit; run it again after `tailor`, `score` or `discover`.",
        "",
        " · ".join(f"**{s}**: {n}" for s, n in counts.items()),
        "",
        "| Status | Score | Auth | Company | Role | Folder | Apply |",
        "|---|---|---|---|---|---|---|",
    ]
    for e in entries:
        score = "-" if e["score"] is None else e["score"]
        role = e["role"].replace("|", "/")
        folder = f"[{e['path']}]({e['path'].replace(' ', '%20')}/)"
        apply = f"[link]({e['apply']})" if e["apply"] else "-"
        lines.append(
            f"| {e['status']} | {score} | {e['work_authorization']} | {e['company']} | {role} | {folder} | {apply} |"
        )
    return "\n".join(lines) + "\n"


DONE_SUFFIX = " - DONE"


def mark_done(entries, root):
    """Rename every `tailored` folder to `<Role> - DONE`; returns the new relative paths.

    `jdstore.job_dir` finds a renamed folder by its `.jobmeta.json` identity, so
    `jd-write` and `jd-similar` keep working. Idempotent, and never overwrites:
    if the target name is taken the folder is left alone.
    """
    renamed = []
    for e in entries:
        if e["status"] != "tailored" or e["path"].endswith(DONE_SUFFIX):
            continue
        old = os.path.join(root, e["path"])
        new = old + DONE_SUFFIX
        if os.path.exists(new):
            continue
        os.rename(old, new)
        e["path"] += DONE_SUFFIX
        renamed.append(e["path"])
    return renamed
